export const SCREENS_MAIN = { TIMER: 'TIMER', TIMER_LIST: 'TIMER_LIST' };
export const SCREENS_TIMER = {
  TIMER: 'TIMER',
  TIMER_LIST: 'TIMER_LIST',
  SETTINGS_TIMER: 'SETTINGS_TIMER',
};
export const SCREENS_SETTINGS = {
  NONE: 'NONE',
  FOCUSE_TIME: 'FOCUSE_TIME',
  SHORT_BREAK: 'SHORT_BREAK',
  LONG_BREAK: 'LONG_BREAK',
  SECTIONS: 'SECTIONS',
};
